version: "2"
services:
    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
####################################################################################################
# Nginx
####################################################################################################
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php


    ####################################################################################################
    # PostgreSQL
    ####################################################################################################
    db:
        image: postgres:16
        ports:
             - 5432:5432
        volumes:
             - .docker/db/data:/var/lib/postgresql/data
             - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
             - POSTGRES_USER=admin
             - POSTGRES_PASSWORD=admin
             - POSTGRES_DB=admin
